import math

Vec3 = tuple[int, int, int]

TICKS_PER_SECOND = 60
SECTOR_SIZE = 16
WALK_SPEED = 6.0
GRAVITY = 20.0
MAX_JUMP_HEIGHT = 1.2
JUMP_SPEED = math.sqrt(2 * GRAVITY * MAX_JUMP_HEIGHT)
TERMINAL_VELOCITY = 50
PLAYER_HEIGHT = 2
